# Generated by Django 4.2.1 on 2023-05-31 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunedin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='isBusiness',
            new_name='is_business',
        ),
    ]
