# Generated by Django 4.2.1 on 2023-06-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunedin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='about_me',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
