# Generated by Django 4.2.1 on 2023-06-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunedin_app', '0002_alter_users_about_me_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
